### ISSUE TITLE
Somethign wrong when upgrading from 2.0.2 to 2.0.3

### ISSUE THREAD

**Issue by huglester** [fuelphp/upload#12]
Hello,

in 2.0.2,
File $container->filename - had filename of the uploaded file; now it is null (in 2.0.3)

What is the correct way to get uploaded filename?

Thanks

**Comment by WanWizard** [comment]
In what exact situation? Succesful upload, or one with errors?

**Comment by WanWizard** [comment]
Did a quick check, but nothing significant seems to have changed in that area.

The filename is set at https://github.com/fuelphp/upload/blob/master/src/File.php#L419, and it gets there as long as the file was uploaded without errors and the path the file has to be written to exists and is accessable.

What has changed is that every save step is now only executed if the previous one went ok, as soon as an error occurs the save process stops.

**Comment by it-can** [comment]
I may have the same issues: https://github.com/fuelphp/upload/issues/14

**Comment by WanWizard** [comment]
Think I found it. Is someone able to test this fix, I'm not in a position to atm.

**Comment by huglester** [comment]
hello,

@WanWizard I can confirm, it works now.
So: 
2.0.2 - works
2.0.3 - does not
dev-master - works

**Comment by WanWizard** [comment]
Ok, thanks for the quick confirmation, I'll tag 2.0.4.
