### ISSUE TITLE
where fuelphp upload v 1.* for fuelphp 1.6 ?

### ISSUE THREAD

**Issue by viyancs** [fuelphp/upload#15]
my upload class didn't working , i think because my upload class not correct version.

**Comment by stevewest** [comment]
"It does not work" is not a valid error report. Please provide more information. What exactly is not working? Also if you are having issues it's recommended to try updating as your issue might have already been solved.

**Comment by viyancs** [comment]
hi steve i was try to using this composer.json to install package fuelphp upload, but it's not working in version  1.6, class still not found .

but when i put fuelphp upload class from another vendor project is working .

**Comment by stevewest** [comment]
Try updating the fuel core to 1.7. Copying the class to the vendor folder is not advised. What is "this composer.json"?

**Comment by viyancs** [comment]
this composer.json mean is using version 1.7 fuelphp upload. i am wondering if I am upgrade into 1.7 fuelphp some function on my current code not working correctly.

**Comment by stevewest** [comment]
There should be no issues with upgrading, we work hard to make sure that new versions stay compatible with existing code. It is recommended that you keep Fuel up to date for security fixes anyway.
